apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prenatal-learning-prod

namePrefix: prod-

resources:
  - ../../base
  - namespace.yaml
  - secrets.yaml
  - ingress.yaml
  - nginx-configmap.yaml

patches:
  - target:
      kind: Deployment
      name: backend
    path: backend-patch.yaml
  - target:
      kind: Deployment
      name: frontend
    path: frontend-patch.yaml
  - target:
      kind: Deployment
      name: mongodb
    path: mongodb-patch.yaml
  - target:
      kind: PersistentVolumeClaim
      name: mongodb-data-pvc
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 10Gi
  - target:
      kind: PersistentVolumeClaim
      name: mongodb-config-pvc
    patch: |-
      - op: replace
        path: /spec/resources/requests/storage
        value: 500Mi
  - target:
      kind: ConfigMap
      name: app-config
    path: configmap-patch.yaml

labels:
  - pairs:
      environment: production
    includeSelectors: false
